### ISSUE TITLE
Problems with Z-transformation

### ISSUE THREAD

**Issue by SelinaNguyen** [UniLuFS2020-ReplicationSeminar/Selina_Lisa_Replication-Paper#3]
Hi Andrea,

we have encountered more problems with normalising the scores.
https://github.com/UniLuFS2020-ReplicationSeminar/Selina_Lisa_Replication-Paper/blob/142bcd674579e76a652714fe54bea382abb0b0b1/Output/Figure1-Senate_Ideal_Points.R#L31-L39
We tried to use the group_by(), summarise() and mutate() function, as you have suggested, but we received error messages.
The first try, it returned "Error: object 'dynamic_ideal' not found" and on the second try, when we specified the dataset (even though this should not be required with the pipe), it returned "Error: Column `dynamic_ideal` must be length 3 (the number of rows) or one, not 9420".
We do not know how to fix these errors.

Then, we realised that in the provided dataset they already had a variable called dynamic_ideal_sd, which could mean that they already standardised the scores and only published the finished dataset on dataverse. However, when computing the sd, we got 1.6 which is not accurate for a standardised variable.
https://github.com/UniLuFS2020-ReplicationSeminar/Selina_Lisa_Replication-Paper/blob/142bcd674579e76a652714fe54bea382abb0b0b1/Output/Figure1-Senate_Ideal_Points.R#L41-L42
In case we are working with already standardised scores, would this still count as a replication? Or do we need to request the original, unstandardised data?

Thank you.

**Comment by DeAngelisA** [comment]
@SelinaNguyen & @Lisa-Thai : here is some reproducible code to standardize a variable by group in the `iris` dataset:

```r
library(tidyverse)
iris %>%     
  group_by(Species) %>% 
  mutate(Sepal.Length_std = (Sepal.Length - mean(Sepal.Length, na.rm = TRUE)) / (sd(Sepal.Length, na.rm = TRUE)))
```

So, as you can see:
1) you should `group_by()` and then call `mutate()` to create the variable. Note: since you want the number of observations to equal the observations in the data, not the number of groups, there is no need for a `summarize()` call. If I suggested that I had probably misunderstood the issue, this is the case for a `mutate()` call.
2) you use `summarize()` to  compute the mean and sd, but as the data is grouped (`group_by()`), you can directly call `mean()` and `sd()`. 
3) Never call the variable names the same as existing functions, as this is likely to result in conflicts (so: don't call the variables `mean` and `sd`. 
4) In a data-pipe block (e.g., your `ideals %>% ...` you should not indicate the data again, so the line 39 in your code has an error, as you should delelte the `ideals$` part. 

Keep me posted, good luck!
A.
